apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iot
  name: a
spec:
  selector:
    matchLabels:
      app: a
  replicas: 1
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: webroot
              readOnly: true
      volumes:
        - name: webroot
          hostPath:
            path: /mnt/apps/a/webroot
