namespace: iot
nameSuffix: -b
commonLabels:
  app: b
resources:
  - ../../base/
replicas:
  - name: http-server-b
    count: 3
configMapGenerator:
  - name: webroot
    files:
    - webroot/index.html