apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress 
  namespace: iot
spec:
  rules:
  - host: a.iot 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: a
            port:
              number: 80
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: a
            port:
              number: 80
