require "../lib/Provisioner"

VAGRANTFILE_API_VERSION = "2"

VM_NAME="#{ENV['USER']}"

VM_SUFFIX_SERVER="S"

VM_APPS_PATH="apps"
VM_APPS_MOUNTPOINT="/mnt/apps"

VM_PROVISION_K3S = "provision/k3s.sh"
VM_PROVISION_DEPLOY= "provision/deploy.sh"

VM_IP_SUBNET="192.168.56"
VM_IP_HOSTID_BASE=110

K3S_SERVER_IP_INTERNAL="#{VM_IP_SUBNET}.#{VM_IP_HOSTID_BASE}"

def provision_server(node, config)
	# Share apps with K3S Server
	config.vm.synced_folder VM_APPS_PATH, VM_APPS_MOUNTPOINT, type: "rsync"

	# Install K3S Server
	config.vm.provision "shell",
		path: VM_PROVISION_K3S,
		args: ["--node-ip", node[:ip]]

	# Deploy K8S Apps
	config.vm.provision "shell",
		path: VM_PROVISION_DEPLOY,
		args: [VM_APPS_MOUNTPOINT]
end

nodes = [
	{
		type: "server",
		name: "#{VM_NAME}#{VM_SUFFIX_SERVER}",
	},
]

provisioner = Provisioner.new(VM_IP_SUBNET, VM_IP_HOSTID_BASE)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "generic/alpine318"

	provisioner.provision nodes, config
end
