apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
nameSuffix: -a
commonLabels:
  app: a
resources:
  - ../../base/
configMapGenerator:
  - name: webroot
    files:
    - webroot/index.html
