require File.join(File.dirname(__FILE__), "..", "lib", "Provisioner")

VAGRANTFILE_API_VERSION = "2"

VM_BOX = "bento/debian-12.5"

VM_NAME = "iot-p3"

VM_RAM_MB = 8096
VM_CPUS = 8

VM_K8S_CONF_PATH = "confs"
VM_K8S_CONF_MOUNTPOINT = "/usr/local/etc/kubernetes"

VM_PROVISION_DOCKER = "scripts/docker.sh"
VM_PROVISION_KUBECTL = "scripts/kubectl.sh"
VM_PROVISION_K3D = "scripts/k3d.sh"
VM_PROVISION_SQUID = "scripts/squid.sh"

VM_PROVISION_USER = "scripts/user.sh"

VM_PROVISION_DEPLOY = "scripts/deploy.sh"

SERVER_DEPS_SYSTEM = [
	VM_PROVISION_DOCKER,
	VM_PROVISION_KUBECTL,
	VM_PROVISION_K3D,
	VM_PROVISION_SQUID,
]

SERVER_DEPS_USER = [
	VM_PROVISION_USER,
]

def provision_server(node, config)
	# Forward Squid HTTP proxy port
	config.vm.network "forwarded_port", guest: 3128, host: 3128

	config.vm.provision "shell",
		inline: "hostnamectl set-hostname #{node[:name]} && sed -i 's/debian-12$/#{node[:name]}/g' /etc/hosts"

	# Sync K8S config
	config.vm.synced_folder "#{VM_K8S_CONF_PATH}/", "#{VM_K8S_CONF_MOUNTPOINT}/",
		type: "rsync",
		create: true

	SERVER_DEPS_SYSTEM.each do |script|
		config.vm.provision "shell",
			path: script
	end

	SERVER_DEPS_USER.each do |script|
		config.vm.provision "shell",
			privileged: false,
			path: script
	end

	config.vm.provision "reload"

	config.vm.provision "shell",
		path: VM_PROVISION_DEPLOY,
		args: [VM_K8S_CONF_MOUNTPOINT]
end

nodes = [
	{
		type: "server",
		name: "#{VM_NAME}",
	},
]

provisioner = Provisioner.new()

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = VM_BOX

        config.vm.provider "virtualbox" do |domain|
          domain.memory = VM_RAM_MB
          domain.cpus = VM_CPUS
        end

	provisioner.provision nodes, config
end
