apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  selector:
    matchLabels:
      run: http-server
  replicas: 1
  template:
    metadata:
      labels:
        run: http-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: webroot
              readOnly: true
      volumes:
        - name: webroot
          configMap:
            name: webroot
